"""
skills/validator.py

Ensures that dynamically generated skills are structurally sound,
semantically unique, and technically safe before saving them to disk.
"""

from safety.policy import SafetyPolicy
from skills.loader import load_skills
import re
from rich.console import Console

console = Console()

class SkillValidator:
    def __init__(self):
        self.policy = SafetyPolicy()
        
    def validate_proposal(self, skill_data: dict) -> dict:
        """
        Validates the JSON proposal generated by the LLM.
        Returns: { "valid": bool, "reason": str }
        """
        
        # 1. Structure Check
        required_keys = ["skill_name", "display_name", "description", "triggers", "bash_script"]
        for key in required_keys:
            if key not in skill_data:
                return {"valid": False, "reason": f"Missing required structural key: {key}"}
                
        script = skill_data["bash_script"]
        if not script.strip().startswith("#!/bin/bash"):
            return {"valid": False, "reason": "Script missing #!/bin/bash shebang."}

        # 2. Safety Check
        # Instead of just checking strings, we'll run the lines through the policy
        lines = script.split("\n")
        for line in lines:
            line = line.strip()
            if not line or line.startswith("#"): continue
            
            check = self.policy.validate_command(line)
            # We strictly block anything that policy says requires confirmation or is outright blocked
            # since generated skills shouldn't house purely dangerous raw logic unattended (ideally).
            # For 'BUILD' mode, this strictly could be relaxed in the future.
            if not check["allowed"]:
                return {"valid": False, "reason": f"Safety violation in script line '{line}': {check['reason']}"}
            if check["requires_confirmation"] and check["risk"] == "dangerous":
                return {"valid": False, "reason": f"Skill contains inherently dangerous logic '{line}'"}

        # 3. Duplicate / Scope Check
        # Heuristic: If another skill already uses 50% of the same triggers, or exact same name.
        existing_skills = load_skills()
        new_triggers = set([t.lower() for t in skill_data.get("triggers", []) if t.strip()])
        new_name = skill_data["skill_name"].lower().replace(" ", "_")
        
        for sk in existing_skills:
            if sk.name.lower().replace(" ", "_") == new_name:
                 return {"valid": False, "reason": f"Skill name collision: {new_name} already exists."}
                 
            existing_triggers = set([t.lower() for t in sk.triggers])
            if existing_triggers and new_triggers:
                overlap = len(new_triggers & existing_triggers)
                if overlap / len(new_triggers) > 0.5:
                    return {"valid": False, "reason": f"High trigger overlap with existing skill: {sk.name}"}

        return {"valid": True, "reason": "Passed."}
